version: "3.3"

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:80"
    environment: 
      - sonar.jdbc.url=somevalue
      - sonar.jdbc.username=someusername
      - sonar.jdbc.password=somepassword
    volumes: 
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions: